[book]
title        = "Digital Insurance"
authors      = ["Sokhibjon Orzikulov <sakhib@orzklv.uz>"]
src          = "src"
language     = "en"

[output.html]
preferred-dark-theme = "ayu"
default-theme        = "light"
cname                = "https://egov.uz"
edit-url-template    = "https://github.com/egov-uz/digital-insurance/edit/main/{path}"
git-repository-url   = "https://github.com/egov-uz/digital-insurance/tree/main/"
mathjax-support      = true
smart-punctuation    = true

[output.html.playground]
editable     = true
line-numbers = true

[output.html.search]
boost-hierarchy     = 2
boost-paragraph     = 1
boost-title         = 2
expand              = true
heading-split-level = 2
limit-results       = 20
use-boolean-and     = true
